### ISSUE TITLE
How to get 401 error object

### ISSUE THREAD

**Issue by Falx** [Yaffle/EventSource#113]
Hi, I am currently using your EventSourcePolyfill because of the Authorization header feature. However I have this issue:

When a user tries to reach our SSE endpoint and the authentication fails, he gets a 401 back with the Www-Authenticate header in the response, containing information to login to our Auth server. 

This Error is seen by your polyfill implementation as it says `EventSource's response has a status 401  that is not 200. Aborting the connection.` However there seems to be no option to get the actual response that was given, which I need to do some automatic login procedures in the client library I am implementing.

Is it at all possible to expose the actual xhr error object?

**Comment by Yaffle** [comment]
status code can be added to the error event - will it work for you?

**Comment by Falx** [comment]
The status code would help me a lot already, but I would still need to be able to access the response headers (www-authenticate in particular) too. Is it possible to add those too?

**Comment by Falx** [comment]
Ok I'll see what I can do this week!

**Comment by Falx** [comment]
It looks to me like this pending pull request has the `status` change already: #109 ?

On the subject of the response header, it seems a bit of a miss when the polyfill allows authorization through headers (which is great!), but can't react to a standardized 401 www-authenticate redirect, without sending an extra request hence introducing another round trip time (especially considering the underlaying xhr has the necessary information already). May I ask the reasons you don't like this feature to be included in the polyfill (out of curiosity, maybe I am missing something). Or would your issue with it be solved if it was implemented as an opt-in configuration option?

Still though: thanks for the work on this poyfill, it has proven to be very valuable and an absolute lifesaver!

**Comment by Yaffle** [comment]
ok, #109 merged

**Comment by Falx** [comment]
So I added a pull request with the headers feature: #114 .
Of course feel free to not merge, just wanted to suggest it, because I think it's a valuable addition.

**Comment by Falx** [comment]
Will you be doing a new release with the #109 merge ? (and possibly the #114)

**Comment by Yaffle** [comment]
@Falx , ok, it should be done.
Note: I have changed the headers field a little bit, please test.

**Comment by Falx** [comment]
Ok, just did some testing on our own SSE api, and this works flawlessly now. Thanks a lot for this merge and release!

**Comment by Yaffle** [comment]
Good, I will close the issue so.

**Comment by davide1995** [comment]
It seems statusCode is not available anymore. On my onerror function this is what the object returns:
```
{
  "type": "error",
  "target": {
    "_listeners": {},
    "url": "http://127.0.0.1:8080/information",
    "readyState": 0,
    "withCredentials": false,
    "headers": {
      "Authorization": "Basic YWRtaW46YWRtaW4="
    }
  },
  "error": {}
}
```

How can I get the status code?

**Comment by Yaffle** [comment]
@davide1995 , it should work, please debug
