### ISSUE TITLE
Failed to call new EventSourcePolyfill(url, cfg) 

### ISSUE THREAD

**Issue by zqkou** [Yaffle/EventSource#117]
As my server side API needs JWT token from header. I was following the example code to setup my authorization header:
```
Custom Headers:
var es = new EventSourcePolyfill('/events', {
  headers: {
    'X-Custom-Header': 'value'
  }
});
```
But I got error message says EventSourcePolyfill is not a constructor:
``` 
__WEBPACK_IMPORTED_MODULE_4_event_source_polyfill_src_eventsource_js__.EventSourcePolyfill is not a constructor
```

The polyfill has been installed by npm install command, and is loaded as:
```
import { EventSourcePolyfill } from 'event-source-polyfill'
```

By the way, I am using this polyfill in VUE with Webpack. Any comments is appreciated.

**Comment by archerbj** [comment]
hi, @Yaffle  I am encountering the same issue. I am trying to use this in my vue webpack project.
may i ask where to put `declare var EventSourcePolyfill: any;` ?
![image](https://user-images.githubusercontent.com/14799336/114123318-a7526780-9924-11eb-9a0e-75802a7ca04a.png)

**Comment by Yaffle** [comment]
@archerbj , I don't know.
The polyfill defines EventSourcePolyfill property on globalThis, so ideally you should be able to import it like:
import "./EventSourcePolyfill.js";
and then use like var es = new EventSourcePolyfill(...);
How does your import look like?

**Comment by archerbj** [comment]
Thanks for your reply! 
I did  

```
import { EventSourcePolyfill } from 'event-source-polyfill'
const source = new EventSourcePolyfill(url, sourcecfg)
// error threw
```
it says EventSourcePolyfill is not a constructor, so sad

**Comment by archerbj** [comment]
I finally make it work like this 

```
import 'event-source-polyfill'
const source = new global.EventSourcePolyfill(url, sourcecfg)

```

thanks for your hint 

> The polyfill defines EventSourcePolyfill property on globalThis (as "a side effect"),
