### ISSUE TITLE
event-source-polyfill does not work with babel-polyfill in Edge

### ISSUE THREAD

**Issue by VictorCazanave** [Yaffle/EventSource#118]
My application must support IE10+/Edge and uses ES6 Promises of babel-polyfill:
* In __IE__ the fetch API is not supported, so event-source-polyfill uses XHR and it works well.
* In __Edge__ I get this error: `Object doesn't support property or method 'finally' at FetchTransport.prototype.open`.

After some debugging,  I noticed that `Promise` has a `finally` method (from babel-polyfill) but not the promise returned by `fetch()`.
If I remove babel-polyfill, the `finally` method is defined by event-source-polyfill and now it also exists in the promise returned by `fetch()`, so it works in Edge (but not in IE since `Promise` doesn't exist for other requests).

It seems it's a [known issue of core-js](https://github.com/zloirock/core-js/issues/178) (used by babel-polyfill): "any call to fetch() will return a native instance instead of a an instance using the polyfill".
They won't fix it but they gave a [workaround](https://github.com/zloirock/core-js/issues/178#issuecomment-192081350) which solved my problem:

```javascript
var _fetch = fetch;
window.fetch = (...args) => Promise.resolve(_fetch(...args));
```

Do you think this fix should/could be included in event-source-polyfill?

I may have time to make a PR, if needed.

__Config__
* event-source-polyfill: 0.0.16
* babel-polyfill: 6.26.0
* browsers: IE11/Edge17

**Comment by Yaffle** [comment]
@VictorCazanave I have added the code to fix this, please check

**Comment by VictorCazanave** [comment]
@Yaffle Thanks for working on it! Recently I'm pretty busy but I'll try to test it this week

**Comment by gsong** [comment]
@Yaffle I tested this and the polyfill works for both IE11 and Edge now. Thank you.

**Comment by Yaffle** [comment]
@gsong, thank you for letting me know
