### ISSUE TITLE
version confusion

### ISSUE THREAD

**Issue by dlong500** [Yaffle/EventSource#119]
The versions listed on github (via git tags) don't seem to be in sync with version info in package.json (and other config files).  For example, the git tag 0.0.17 has a version of 0.0.16 in package.json.  Can we get a canonical version number across every source of information for clarity?  Also, a new npm release would be awesome given the last commit dealing with UMD builds.  Thanks!

**Comment by Yaffle** [comment]
it is very hard to update versions... as I don't like to spend time reading the docs of bower, npm and all other things and then trying to publish new version after every change... It is annoying that you have to keep in mind the order of update steps and what json files to update...

**Comment by Yaffle** [comment]
I have tried to update the version and publish - please check

**Comment by dlong500** [comment]
Thanks!  It all seems to be fine now.

**Comment by Yaffle** [comment]
good, thanks for the quick update
