### ISSUE TITLE
Upgrading to v1.x.x fails to load on Edge/IE11

### ISSUE THREAD

**Issue by EPinci** [Yaffle/EventSource#121]
Hello!
I have a VUE/Webpack project that uses this EventSource polyfill on Edge/IE11.
Version 0.0.16 works fine.
If I upgrade to v1.0.3, the EventSource object doesn't get created (verified from browser console) and, subsequently, HMR fails as well.
Am I missing something in the version change?
Thank you.

**Comment by Yaffle** [comment]
I know nothing about VUE/Webpack/HMR, please provide a code changed needed to fix the problem

**Comment by EPinci** [comment]
Hey, first of all, thank you for getting back to me!

I'm actually new to those technologies as well and I'm still ramping up on debugging it.
I know that this is the result of just changing the version tag in the package.json (no changes in scripts or bundling process).
I cannot see any error on the console but the HMR complaining about the missing EventSource support after the version change and that got me to try to query for the object existence.
I'm comparing the two javascript from v0.0.16 and v1.0.3 and I can't find anything that catches my eye if not for the closing block that I cannot reason out.
Any chance you changed the way the polyfill has to be initialized?

Thank you!

**Comment by Yaffle** [comment]
there is another similar issue - https://github.com/Yaffle/EventSource/issues/117
