### ISSUE TITLE
Ipv6 With Eventsource

### ISSUE THREAD

**Issue by BiditPakrashi** [Yaffle/EventSource#132]
We saw an issue with eventsource in ipv6 network. If I change my laptop network to ipv4 and open my webpage then it is working fine but If I move to ipv6 network I saw a 500 error status .

All our backend is running on ipv4.

I am using react js with Eventsource polyfill and our backend is in Spring SSE emiter .  I am not sure if Server sent event is compatible with ipv6  or it is an lib issue.

**Comment by Yaffle** [comment]
Could you try to use fetch API or native EventSource to request the same URL?
