### ISSUE TITLE
Transport: window.XMLHttpRequest

### ISSUE THREAD

**Issue by cszasz** [Yaffle/EventSource#134]
Hi,

It seems that EventSourcePolyfill doesn't work with the following setting:
     Transport: window.XMLHttpRequest

Any idea why?

Best regards,
Csaba

**Comment by Yaffle** [comment]
What web browser are you using?

**Comment by Yaffle** [comment]
Do you set the event listener after the construction of the object? Thinks, like `alert(1)` can influence here.

**Comment by cszasz** [comment]
I set it as an option of the constructor.
What I see, is that it hangs because it cannot process the partial responses.
On the server side I see the connection which is not aborted later, still on the client side I never get the open event.

**Comment by Yaffle** [comment]
@cszasz , Internet Explorer 9 does not fire events for "partial responses" if I recall correctly

**Comment by cszasz** [comment]
I am testing it on iOS, Safari

**Comment by cszasz** [comment]
What I don't understand is what can be the difference between the default global.HttpXMLRequest and the window.HttpXMLRequest I pass over. Seemingly they are similar, but the windows.HttpXMLRequest dows not behave the same with "text/event-stream".

**Comment by Yaffle** [comment]
Note: the polyfill uses "fetch API" on modern Safari

**Comment by cszasz** [comment]
I understand, but can it happen that this "fetch API" does not work with window.HttpXMLRequest while it works with the HttpXMLRequest used by default by the polyfill?

**Comment by Yaffle** [comment]
@cszasz , when "Transport" is not passed, XMLHttpRequest is not used at all

**Comment by cszasz** [comment]
I pass the Transport as the option of the EventSourcePolyfill constructor (I call it explicitly).

if the Transport is not set then I thought that the getBestTransport will return the default XMLHttpRequest
```
function getBestTransport() {
    return (XMLHttpRequest != undefined && ("withCredentials" in XMLHttpRequest.prototype)) || XDomainRequest == undefined
      ? XMLHttpRequest
      : XDomainRequest;
  }
```

**Comment by Yaffle** [comment]
@cszasz , the value of that function is not used, the code is not well written...
