### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by dayanfcosta** [Yaffle/EventSource#139]
Hi, I'm facing a error when I create an EventSourcePolyfill, and it's suposed to thrown an error, but even using a try-catch block around my initialization I'm not able to threat the error, I just wanted to make a loop that, when initializing and throwing an error, it just should try to initalize again, a recursion. I think that it's related to this block of code:

```
function throwError(e) {
    setTimeout(function () {
      throw e;
    }, 0);
  }
```

My code is like this:

```
startListener() {
    if (!this.eventSource) {
      try {
        this.initEventSource();
      } catch (err) {
        console.log('Error on init eventSource: ', err);
        console.log('Initing it again...');
        this.initEventSource();
      }
    }
  }

  private initEventSource() {
    this.eventSource = new EventSourcePolyfill(this.serviceUrl, {headers: {'Authorization': this.tokenService.token()}});
    this.eventSource.onmessage = message => {
      // const event = message.data as TranslationUpdateEvent;
      // this.remoteTranslationService.removeLocal(event);
      console.log(message.data);
    };
    this.eventSource.onerror = error => console.log(error);
  }
```

**Comment by Yaffle** [comment]
What is the error message?
`throwError` is for errors thrown by event listeners...

**Comment by dayanfcosta** [comment]
@Yaffle the error message is : ` EventSource's response has a status 707 unknown that is not 200. Aborting the connection.` It's because at this time, I'm not authenticated and I'd like to do some recursion to always verify if there is a valid token.

**Comment by dayanfcosta** [comment]
> What is the error message?
> `throwError` is for errors thrown by event listeners...

The error ocurrs during the construction of the object `EventSourcePolyfill` into the `start()` method

**Comment by Yaffle** [comment]
Please listen for the "error" event:
```
this.eventSource.onerror = error => {
  if (this.eventSource.readyState === EventSource.CLOSED) {
    this.initEventSource();
  }
};
```

**Comment by dayanfcosta** [comment]
I tried to listen to `onerror` but I didn't have success, it stills printing the error on console and not calling again the method `initEventSource()`, I tried to put a breakpoint there and it isn't hitted

**Comment by dayanfcosta** [comment]
Sorry, my bad, it works! Thank you!
