### ISSUE TITLE
Compatibility with RetroZilla

### ISSUE THREAD

**Issue by tobiastromm** [Yaffle/EventSource#141]
Can this please work with https://github.com/rn10950/RetroZilla/ browser?

* rawUa: Mozilla/5.0 (Windows; U; Windows NT 4.0; en-US; rv:1.8.1.24) Gecko/20190223 RetroZilla/2.2 SeaMonkey/1.1.19 Firefox/2.0.20
* string:
* family: SeaMonkey
* major: 1
* minor: 1
* patch: 19
* device: Other 0.0.0

Thank you.

**Comment by Yaffle** [comment]
would be nice to test and debug.
You could try to `node tests\server.js` then open http://localhost:8002 and capture the results.
Is it the same as Firefox 2 ? May be, I could download old Firefox and test....

**Comment by Yaffle** [comment]
@tobiastromm , https://github.com/Yaffle/EventSource/commit/ddddda0fe98a4a814f969322fac3c19e33bc2eba

**Comment by tobiastromm** [comment]
@Yaffle, working exactly as expected.

Thank You soo much.

Just test it with https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_sse example code.

<a href="https://ibb.co/FmCVfGd"><img src="https://i.ibb.co/RYdyMLJ/Retro-Zilla-Event-Source.png" alt="Retro-Zilla-Event-Source" border="0"></a>

**Comment by tobiastromm** [comment]
Just a question.

Appears that old browsers do not support "var data = JSON.parse(e.data);"

Any alternative to that:

   source.addEventListener('novaMensagem', function(e) {
      var data = JSON.parse(e.data);
      alert ('Mensagem: ' + data.mensagem + ' , Data\Hora: ' + data.mensagemNotificacao);
   }, false);

**Comment by Yaffle** [comment]
@tobiastromm , you might try to use a polyfill for JSON - https://github.com/douglascrockford/JSON-js/blob/master/json2.js

**Comment by tobiastromm** [comment]
@Yaffle , working exactly as expected!!! Again, thank you soo much. Thank you for your kindness and support. I am closing this.

**Comment by Yaffle** [comment]
@tobiastromm , thank you! Now it works in Firefox 2 :-)
