### ISSUE TITLE
supportsStreamOption error Message

### ISSUE THREAD

**Issue by SantoJambit** [Yaffle/EventSource#149]
Currently, there is a log output, which prints a full stack trace whenever the TextDecoder polyfill is being used.

Would it be acceptable to change this to a one-liner `"TextDecoder does not support streaming option. Using polyfill instead."` or even suppress the message altogether?

Otherwise I'm getting spammed with stacktraces during my test-runs, which makes the log pretty hard to read.

Aside from that, we would like to not have errors in the console unless they actually cause invalid behaviour.

**Comment by Yaffle** [comment]
@SantoJambit , are you OK with the usage of `console.debug(error)` instead?

**Comment by SantoJambit** [comment]
@Yaffle that doesn't change anything for the better.

In our code-base we use [loglevel](https://www.npmjs.com/package/loglevel) to prevent such informations from leaking where they should not be, but I don't think one console statement is worth introducing a new dependency in this case.

**Comment by Yaffle** [comment]
@SantoJambit , right, what about `console.debug("TextDecoder does not support streaming option. Using polyfill instead.")` ?

**Comment by SantoJambit** [comment]
@Yaffle yes, that would be good.

**Comment by SantoJambit** [comment]
@Yaffle when can we expect a release?

**Comment by Yaffle** [comment]
@SantoJambit , just released, thanks for the reminder
