### ISSUE TITLE
heartbeatTimeout checks with shorter delays

### ISSUE THREAD

**Issue by jtempl** [Yaffle/EventSource#151]
Currently, the heartbeatTimeout is checked in fix intervals. For a heartbeatTimeout T a missing heartbeat is discovered within the interval [T .. 2 * T] depending on when the last activity happend with respect to the fixed heartbeat checking interval. This should be reduced to just T by taking the timestamp of the last activity into account when starting a new timer with setTimeout.

**Comment by Yaffle** [comment]
@jtempl , please make a pull request with the change

**Comment by jtempl** [comment]
a [pull request](https://github.com/Yaffle/EventSource/pull/152) has been created
