### ISSUE TITLE
EventSourcePolyfill - How to limit the retires if the call failed

### ISSUE THREAD

**Issue by ariel262626** [Yaffle/EventSource#153]
Hi, 
If i set eventListener to eventSource (EventSourcePolyfill object) and the call is failed (server is down, ...) the API call retries unlimited times to make the call. 

Thanks.

**Comment by Yaffle** [comment]
@ariel262626 , the native implementation tells, that "retry: <integer>\n" can be used in the event stream, just set it to some big number

**Comment by ariel262626** [comment]
Thanks, where can i find that configuration setting?

**Comment by Yaffle** [comment]
@ariel262626 , https://javascript.info/server-sent-events#reconnection
