### ISSUE TITLE
How to handle errors?  Non-minified version prints `undefined` error

### ISSUE THREAD

**Issue by mkrakiewicz** [Yaffle/EventSource#159]
Hi, 
I'm trying to subscribe with auth to Mercure. The native EventSource works OK without authentication. But I need auth so I'm trying to use this polyfill.

TLDR: the minified version of this lib (1.0.20) works OK, but development version throws me errors constantly. The minified version has stripped `console.error` calls but I would like to handle this properly if there is something wrong.

When I use non-minified version of this lib I get errors every ~15 seconds:

<img width="591" alt="Zrzut ekranu 2020-09-24 o 10 51 06" src="https://user-images.githubusercontent.com/17594718/94123638-55e4fe00-fe54-11ea-9322-1741d0084c31.png">

<img width="535" alt="Zrzut ekranu 2020-09-24 o 10 53 49" src="https://user-images.githubusercontent.com/17594718/94123617-4f568680-fe54-11ea-8605-d38253c80476.png">

The code still works, but the errors are unexpected. 

How to handle those errors / reconnects properly? Because this doesn't happen in the native EventSource.

EDIT:

I've degraded version to 1.0.19 and the console log is removed and I can use a listener to get errors manually.

**Comment by dlong500** [comment]
@Yaffle It looks like the console logging on that particular line was only added in v1.0.20.  Can you clarify why it is needed?

**Comment by Yaffle** [comment]
looks like that line should be removed
