### ISSUE TITLE
Type error : Fail to fetch

### ISSUE THREAD

**Issue by priyapitroda1712** [Yaffle/EventSource#166]
![image](https://user-images.githubusercontent.com/52781916/110613993-e079a980-81b7-11eb-9fd9-30d68270e3cf.png)

I have set heartbeatTimeout value to 5 mins even though API trigger every 1 mins with error : "Type error : Fail to fetch"
Can anyone help :
   1. to find out the cause for this issue and
   2. why heartbeatTimeout is not working in this case.
Thanks

**Comment by priyapitroda1712** [comment]
Thanks Yaffle for response.
Yes I receive onerror event:

 this.eventSource.onerror = error => {  // error is "Type error : Fail to fetch"})

**Comment by Yaffle** [comment]
Could you try without the polyfill?

**Comment by priyapitroda1712** [comment]
Hi @Yaffle 

Yes I have tried without polyfill, getting timeout error.

I have a question related to pollyfil, I have set heartbeatTimeout to 5 mins. However the API is being called every 1 min. I was expecting that by setting the heart beat timeout to 5 mins, a separate call would be made to the API after 5 mins of not getting any response. 
Can you please help me understand this behavior?

**Comment by Yaffle** [comment]
@priyapitroda1712 , there is another thing - "retry" timeout, which is 1 second by default.
The native EventSource allows to set it from the event stream itself by using: 
retry: 10000\n
And the polyfill allows to set it the same way.
This means, that it will try to reconnect after 1 second (by default) after the "fetch error".
"heartbeatTimeout" is to detect disconnects on the application level.
The polyfill uses "Fetch API" inside, I don't know if the browser has some timeout here.

**Comment by priyapitroda1712** [comment]
Thanks @Yaffle 
Yes, may be the browser has some timeout here.

**Comment by priyapitroda1712** [comment]
Thanks @Yaffle for your all support
I am closing this as I'm able to solved this issue by continuously open the connection from API side until not getting the expected response.

**Comment by leik-software** [comment]
Hey @priyapitroda1712 ,
I have the same issue. Can you tell more about how you solved it? 
Thanks,
Alex

**Comment by leik-software** [comment]
ok thanks, I understand!
