### ISSUE TITLE
Not receiving error status and message on ErrorEvent

### ISSUE THREAD

**Issue by mihai-hoinaru** [Yaffle/EventSource#170]
Receiving only error, target (EventSourcePolyfill) and type: "error". But I'd like to know the status code as well...
I'm using https://www.npmjs.com/package/event-source-polyfill, v1.0.24

**Comment by Yaffle** [comment]
@mihai-hoinaru do you have error property?
It may be there is no status code as there is a problem before receiving the HTTP response.

**Comment by mihai-hoinaru** [comment]
@Yaffle , the error property is undefined
