### ISSUE TITLE
Issue passing Authorization header in old Safari?

### ISSUE THREAD

**Issue by paolodina** [Yaffle/EventSource#171]
Hi, I'm using the Authorization header with EventSource polyfill. Everything works great with Chrome, Firefox and recent Safari, but with Safari 9 the header is not sent to the server (it's missing from the browser request). [I see](https://en.wikipedia.org/wiki/Safari_version_history) that only since Safari 10.1 the Fetch API is supported. Could this be the reason? And eventually is there anything I can do to fix/workaround the issue?

If it matters, I create the instance this way:

```
new EventSourcePolyfill(this.url, {
    withCredentials: this.withCredentials,
    lastEventIdQueryParameterName: 'last-id',
    headers: { Authorization: 'Token the_token' },
});
```

**Comment by Yaffle** [comment]
it is using XMLHttpRequest#setRequestHeader, not sure if there are some bugs or it does not allow to set Authorization

**Comment by paolodina** [comment]
It turned out it was an error in my code! Sorry for bothering, thanks for the polyfill.

**Comment by Yaffle** [comment]
@paolodina , was it on the server side?
Thanks for closing the issue

**Comment by paolodina** [comment]
Nope, it's client side. I still don't know where exactly the mistake is, but a friend told me that before the last client refactoring (which was big) it stopped working.

**Comment by Yaffle** [comment]
@paolodina because the client side code looks good
