### ISSUE TITLE
onmessage event not triggering after connection is opened

### ISSUE THREAD

**Issue by lgahdl** [Yaffle/EventSource#196]
Hi guys, I want to know if I'm doing something wrong in my code.
I'm using the EventSourcePolyfill because I need to send an Authorization Header with the request, with "curl" my request works good, I'm receiving the messages, but in the browser something works wrong, I don't receive any message and I don't know where is the problem.

Code of my Frontend EventSource:
```
import { EventSourcePolyfill } from 'event-source-polyfill'

...

export const useSSE = (url) => {
  const eventSource = new EventSourcePolyfill(url, {    headers: {
      Authorization: `Bearer ${localStorage.getItem("TOKEN")}`,
    },
  });
  eventSource.onmessage = (event) => {
    console.log(event)
  }
  eventSource.onerror = (event) => {
    console.log(event)
  }
  eventSource.onopen = (event) => {
    console.log(event)
  }
  eventSource.addEventListener("open", console.log);
  eventSource.addEventListener("message", console.log);
  eventSource.addEventListener("closed", console.log);
  eventSource.addEventListener("retrying", console.log);
  eventSource.addEventListener("end", console.log);
  eventSource.addEventListener("error", console.log);
  return () => {
    eventSource.close()
  }
}
```

curl:
![image](https://user-images.githubusercontent.com/50002794/145615039-31b7a563-ee6a-43cf-a857-c1163621c8c9.png)

chrome dev tools:
![image](https://user-images.githubusercontent.com/50002794/145615207-6b95430e-0c42-405f-bd99-3d4fc9aa550a.png)

**Comment by lgahdl** [comment]
PS: The server is using Spring Web Flux and is not providing the ```Last-Event-ID``` header, can it be the cause?

**Comment by lgahdl** [comment]
FOUND IT!
my event was "qualifier-events" where it should be "message"

**Comment by Yaffle** [comment]
The EventSource tab in DevTools is not working with polyfill, may be sone debugging should be added instead.
