### ISSUE TITLE
Is this still a polyfill?

### ISSUE THREAD

**Issue by xsrvmy** [Yaffle/EventSource#207]
Definition of polyfill by Mozilla:
"A polyfill is a piece of code (usually JavaScript on the Web) used to provide modern functionality on older browsers that do not natively support it."

When you add code doing more than what the modern actually API does, it is no longer really a polyfill.

#199  #205

**Comment by TheOtterlord** [comment]
Very true. No matter someones views on malware/protestware and whether this fits the definition, this is definitely no longer a polyfill and shouldn't be used as one.

**Comment by Yaffle** [comment]
Please change the definition so

**Comment by TheOtterlord** [comment]
Change the definition of **polyfill** to include unexpected, undocumented behavior?
