### ISSUE TITLE
npm ERR! ERESOLVE could not resolve

### ISSUE THREAD

**Issue by jclivi** [Yaffle/EventSource#222]
npm install event-source-polyfill
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: taroApp@1.0.0
npm ERR! Found: react-native@0.72.4
npm ERR! node_modules/react-native
npm ERR!   peer react-native@">=0.47.0" from react-native-root-toast@3.5.1
npm ERR!   node_modules/react-native-root-toast
npm ERR!     react-native-root-toast@"^3.0.1" from @tarojs/taro-rn@3.6.15
npm ERR!     node_modules/@tarojs/taro-rn
npm ERR!       @tarojs/taro-rn@"^3.3.10" from the root project
npm ERR!   peer react-native@"*" from react-native-svg@13.13.0
npm ERR!   node_modules/react-native-svg
npm ERR!     peer react-native-svg@">=6.5.1" from react-native-svg-transformer@0.14.3
npm ERR!     node_modules/react-native-svg-transformer
npm ERR!       react-native-svg-transformer@"^0.14.3" from @tarojs/rn-supporter@3.6.15
npm ERR!       node_modules/@tarojs/rn-supporter
npm ERR!         @tarojs/rn-supporter@"3.6.15" from @tarojs/rn-runner@3.6.15
npm ERR!         node_modules/@tarojs/rn-runner
npm ERR!   3 more (react-native-svg-transformer, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! react-native@"^0.64.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@"17.0.1" from react-native@0.64.4
npm ERR!   node_modules/react-native
npm ERR!     react-native@"^0.64.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Yaffle** [comment]
@jicvi there are no dependency on react-native in the project, at least direct
