### ISSUE TITLE
How can i detect connection is closed to refresh JWT tokens ?

### ISSUE THREAD

**Issue by eguvenc** [Yaffle/EventSource#230]
Every request i send a JWT token at headers.
When the connection is closed with 401 reason i want to recreate the EventSource object with new token.

Is there any way to detect connection is open or not ?

**Comment by Yaffle** [comment]
Listen for error event, you can even change the header by changing the property value

**Comment by eguvenc** [comment]
I tried to listen error event, it always come null even if connection closed

**Comment by Yaffle** [comment]
See https://github.com/Yaffle/EventSource/issues/137#issuecomment-599061039

**Comment by eguvenc** [comment]
thanks, it works fine.
```
eventSource.onerror = function (event) {
  if (event.status == 401) {

  }        
};
```
