### ISSUE TITLE
Does EventSource block Firefox WebDriver?

### ISSUE THREAD

**Issue by suin** [Yaffle/EventSource#45]
I work on a project which uses Yaffle/EventSource and server-sent events. I came across a problem while trying to test the SSE functionality with Selenium Firefox WebDriver. The problem is that WebDriver's any operations(ex, `findElement`, `getCurrentUrl` and so on) are blocked while EventSource's connection is open.

I tried to fix this problem, but I couldn't. Does anyone have any idea to avoid this blocking issue?

## Codes to reproduce

The followings are the code that  reproduces this problem.

This PHP code below provides both functionalities of server side and client side of server-sent events. This file is hosted as `http://192.168.0.77/tests/stream.php`. 

I wrote two client code for comparison. The first one uses `XMLHtttpRequest` and another uses `EventSource`. 

* XMLHtttpRequest: WebDriver's operations are not blocked.
* EventSource: WebDriver's operations are blocked.

```php
<?php

function stream()
{
    // server side code
    header("Content-Type: text/event-stream");
    header("Cache-Control: no-cache");
    header("Access-Control-Allow-Origin: *");

    for ($i = 5; $i >= 0; $i--) {
        echo 'data: ' . $i . "\n\n";
        ob_flush();
        flush();
        sleep(1);
    }
}

if (isset($_GET['stream'])) {
    stream();
    exit;
}

$use = isset($_GET['use']) ? $_GET['use'] : "xhr";

// following is client side code.
?>
<!DOCTYPE html>
<h1>Stream (<?= $use ?>)</h1>
<div>Response:</div>
<pre id="response"></pre>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://raw.githubusercontent.com/Yaffle/EventSource/63b50221ea2c9440fae84d6f98895b911db43807/eventsource.js"></script>
<script>
    (function () {
        var STREAM_URL = './stream.php?stream';

        // client code one
        function xhr() {
            var xhr = new XMLHttpRequest();
            xhr.open('GET', STREAM_URL);
            xhr.seenBytes = 0;
            xhr.onreadystatechange = function () {
                if (xhr.readyState > 2) {
                    var newData = xhr.responseText.substr(xhr.seenBytes);
                    $("#response").append(newData);
                    xhr.seenBytes = xhr.responseText.length;
                }
            };
            xhr.send();
        }

        // client code two
        function eventsource() {
            var es = new EventSource(STREAM_URL);
            es.addEventListener('message', function (event) {
                $("#response").append(event.data + "\n");
                if (event.data == 0) es.close();
            }, false);
        }

        <?= $use ?>(); // function is dynamically provided by PHP.
    }());
</script>
</html>
```

This is Scala code which drives Selenium WebDriver.

```scala
import org.openqa.selenium.By
import org.openqa.selenium.remote.{ DesiredCapabilities, RemoteWebDriver }
import org.scalatest.FunSuite

class ServerSentEventsSpec extends FunSuite {
  test("with `XMLHttpRequest`") {
    val hubUrl = "http://192.168.0.1:5556/wd/hub"
    val driver = new RemoteWebDriver(new java.net.URL(hubUrl), DesiredCapabilities.firefox())
    driver.get("http://192.168.0.77/tests/stream.php?use=xhr")

    println(new java.util.Date())
    val text = driver.findElement(By.xpath("//html")).getText // This line is not blocked.
    println(text)
    println(new java.util.Date())

    driver.quit()
  }
  
  test("with `EventSource`") {
    val hubUrl = "http://192.168.0.1:5556/wd/hub"
    val driver = new RemoteWebDriver(new java.net.URL(hubUrl), DesiredCapabilities.firefox())
    driver.get("http://192.168.0.77/tests/stream.php?use=eventsource")

    println(new java.util.Date())
    val text = driver.findElement(By.xpath("//html")).getText // This line is blocked for about 5 seconds!
    println(text)
    println(new java.util.Date())

    driver.quit()
  }
}

```

### Output of the test case "with `XMLHttpRequest `"

In this case, Firefox WebDriver could immediately get the text of the web page .

```
Thu Nov 27 07:59:39 UTC 2014
Stream (xhr)
Response:
data: 5
Thu Nov 27 07:59:39 UTC 2014
```

### Output of the test case "with `EventSource`"

In this case, as you can see, Firefox WebDriver waited until `EventSource` received all events.

```
Thu Nov 27 07:59:32 UTC 2014
Stream (eventsource)
Response:
5
4
3
2
1
0
Thu Nov 27 07:59:37 UTC 2014
```

## Versions

* Firefox version: 31.0
* Mac OSX: 10.10
* org.seleniumhq.selenium selenium-remote-driver 2.37.1
* org.seleniumhq.selenium selenium-firefox-driver 2.42.2

**Comment by bsy** [comment]
@suin any updates on fixing this?

**Comment by AlexioVay** [comment]
Want to know if there is a fix also.

**Comment by Yaffle** [comment]
@bsy, @AlexioVay 
Could you please check, if line 507 is reached https://github.com/Yaffle/EventSource/blob/master/eventsource.js#L507 ?

Could you please try to change `if` condition to make line 507 reached/unreached and test WebDriver?

If line 507 is not reached, it is a bug with of native EventSource and we can only workaround it somehow.

**Comment by trussolytro** [comment]
I see that line being reached. Any other ideas?

**Comment by Yaffle** [comment]
Please check with latest code.
Please check without polyfill.
