### ISSUE TITLE
SECURITY_ERR in PhantomJS

### ISSUE THREAD

**Issue by Paxa** [Yaffle/EventSource#49]
I'm getting js error `SECURITY_ERR: DOM Exception 18` on in place:

```js
  var isEventSourceSupported = function () {
    if (global.EventSource !== undefined) {
      try {
        var es = new global.EventSource("data:text/event-stream;charset=utf-8,");
        es.close();
        return es.withCredentials === false &&
               es.url !== ""; // to filter out Opera 12 implementation
      } catch (error) {
        throwError(error);
      }
    }
    return false;
  };
```

By line `es.close();` https://github.com/Yaffle/EventSource/blob/62be4ad02a5b78db85fc0ee5d8fd5fc32b1456dd/eventsource.js#L490

PhantomJS 1.9.8

**Comment by Yaffle** [comment]
possibly, the condition in the `if` should be modified to do not pass PhantomJS...

**Comment by 3rd-Eden** [comment]
Instead of a `throwError(error)` it should just `return false` there so the polyfill will kickin when the native version throws errors.

**Comment by Yaffle** [comment]
this was done to not hide the error:
`throwError` uses `setTimeout` to rethrow the error asynchronously, so `return false` will be executed.

anyway, https://github.com/Yaffle/EventSource/pull/56 removed `throwError`
