### ISSUE TITLE
eventsource.js contains security bridges

### ISSUE THREAD

**Issue by Vitalidov** [Yaffle/EventSource#50]
eventsource.js file contain following security bridges:

User Input validation, Code injection.

Is any mitigation plan exists? secure version or hardening guide?

Thanks

**Comment by Yaffle** [comment]
Really? Can you please provide more information?

**Comment by Vitalidov** [comment]
Hello Viktor,

Thanks for the quick answer.

We get PenTest report with some issues, for example:

The file eventsource.js interprets unvalidated user input as source code on
line 42:

eventsource.js , line 18 - Read ~LocalScope.response.socket
eventsource.js , line 18 - Assignemnt to ~this._stream
eventsource.js , line 27-  Assignemnt to ~LocalScope.self
eventsource.js , line 42 - Assignemnt to ~scope


The assignments performed without input validation.

Could you please look on it?

BR
Vitaly

**Comment by Yaffle** [comment]
>The assignments performed without input validation.
Do not think it is needed.
