### ISSUE TITLE
Weird relation: if (n !== n)

### ISSUE THREAD

**Issue by uberstud87** [Yaffle/EventSource#51]
Good day!

I was reading through eventsource.js and saw something strange at [Line 133](https://github.com/Yaffle/EventSource/blob/62be4ad02a5b78db85fc0ee5d8fd5fc32b1456dd/eventsource.js#L133).

```javascript
Line 131:  function getDuration(value, def) {
Line 132:    var n = value;
Line 133:    if (n !== n) {
Line 134:      n = def;
Line 135:    }
Line 136:    return (n < MINIMUM_DURATION ? MINIMUM_DURATION : (n > MAXIMUM_DURATION ? MAXIMUM_DURATION : n));
Line 137:  }
```

Is there any mistake here? Seems like the if statement will never be false.
It was changed in the https://github.com/Yaffle/EventSource/commit/cae1b45833732da2e1c51a33ed6ae7d64baf71e5 or https://github.com/Yaffle/EventSource/commit/cae1b45833732da2e1c51a33ed6ae7d64baf71e5#diff-e3467803443c0c8c621be962b3a7127b for convenience.

It was previously the following.
```javascript
Line 131:  function getDuration(value, def) {
Line 132:    var n = Number(value) || def;
Line 133:    return (n < MINIMUM_DURATION ? MINIMUM_DURATION : (n > MAXIMUM_DURATION ? MAXIMUM_DURATION : n));
Line 134:  }
```

Regards,
William

**Comment by Yaffle** [comment]
This is for `NaN` value.
