### ISSUE TITLE
Problems with self signed certificates

### ISSUE THREAD

**Issue by hstaudacher** [Yaffle/EventSource#52]
I'm using the EventSource polyfill during development with a server that uses a self signed certificate when connecting via HTTPS. Everytime I use EventSource an "error" event is thrown immediately using those HTTPS connection. 

Maybe I have configured it wrong. So, a point in the right direction great ;)

**Comment by Yaffle** [comment]
@hstaudacher , did you visit this site in a browser tab and accept the untrusted connection ?
I do not know how to solve this. IE and Opera 12 shows a dialog to accept connection, but Chrome and Firefox do not do this.

**Comment by hstaudacher** [comment]
Yes, I'm using chrome and accepted the connection the first time it connects.

**Comment by Yaffle** [comment]
@hstaudacher , I checked and it works for me, if I "accept the connection".

**Comment by hstaudacher** [comment]
Alright, thanks for validating. A few minutes ago I just found out that this may be a server side issue. So, sorry for bothering.

**Comment by Yaffle** [comment]
ok
