### ISSUE TITLE
Update npm release

### ISSUE THREAD

**Issue by jareware** [Yaffle/EventSource#54]
The [latest release](https://github.com/Yaffle/EventSource/releases/tag/0.0.4) doesn't seem to be available on [npm](https://www.npmjs.com/package/event-source-polyfill) yet. :)

Cheers!

**Comment by Yaffle** [comment]
sorry, it is too hard to support all this

**Comment by jareware** [comment]
It's quite simple, just go ahead and:
```
$ git checkout 0.0.4
$ vim package.json # to update the "version" property to "0.0.4"
$ npm publish
```
That's it! :)

**Comment by Yaffle** [comment]
@jareware , thanks, I do not think 0.0.4 has significant changes, will do for 0.0.5

**Comment by jmar777** [comment]
Hey, just trying to bump this request. This polyfill is amazing, and it would be really nice to have it fit into our build system a little more naturally. The version published to npm right now appears to still be v0.0.1.  Thanks!

**Comment by Yaffle** [comment]
Done, please check

**Comment by jmar777** [comment]
```
$ npm show event-source-polyfill version
0.0.5
```

Perfect, thanks so much!

**Comment by Yaffle** [comment]
You're Welcome
