### ISSUE TITLE
XDR is used on same domain request (IE9)

### ISSUE THREAD

**Issue by FritsvanCampen** [Yaffle/EventSource#57]
EventSource has a long-polling fallback for browsers that don't support event streams.
EventSource also supports cross-domain-requests.
In IE9 you need to make an XDomainRequest (instead of XMLHttpRequest) if you want to do a cross-domain-request.

The problem is that code doesn't check properly whether the request _is_ a cross-domain-request when deciding between XDR or XHR, it just always uses XDR (in IE9). This is important because an XDR requires a CORS policy (Allow-Access-* headers). It's silly to _require_ a CORS policy for same-domain-requests. Not settings the CORS policy headers will cause IE9 to discard the response.

De decision is:

    Transport = isCORSSupported ? XHR : (XDR !== undefined ? XDR : undefined)

As you can see it just checks whether CORS is supported, not wether CORS is required. Later on when `Transport` is about to be used there is:

    var withCredentials = isCORSSupported && options !== undefined && Boolean(options.withCredentials);

We can use `withCredentials` to decide between XDR or XHR:

    var xhr = new Transport(); // always yields XDR (in IE9)
    // change to:
    var xhr = withCredentials ? new Transport() : new XHR();

This fixes the problem but I feel like a refactor is required.

What if a cross-domain-request is required but is not supported?

---

This is related to: https://github.com/Yaffle/EventSource/issues/41 but the suggestion to force XHR is silly, it should use whatever is required (but prefer XHR). I think my fix also solves that issue.

**Comment by Yaffle** [comment]
Only "long-polling" is possible with XHR in IE8-IE9. So XDR may be better even for single domain requests sometimes. I am OK with new option.

**Comment by FritsvanCampen** [comment]
XDR shouldn't be used on same domain requests.

**Comment by Yaffle** [comment]
> XDR should never be used on same domain requests. There doesn't need to be an option for this.

Why? XDR can be better (allows streaming)

I have updated this repo.
use `new EventSource(url, {Transport: XMLHttpRequest})`
