### ISSUE TITLE
XHR is neglected as a Transport if CORS support is not available, failing to use the lib on such platforms.

### ISSUE THREAD

**Issue by ncv-dev** [Yaffle/EventSource#60]
The following code statement -
```javascript
  var isXHR = isCORSSupported;
  var Transport = isCORSSupported ? XHR : (XDR != undefined ? XDR : undefined);
```

is making these assumptions:
* XHR always support CORS
* If CORS is not supported then Transport is possibly XDR, even though XHR is available.

This results in failure to use this polyfill where XHR does not have CORS support.

**Comment by Yaffle** [comment]
@ncv-dev , 
you are right, this was done intentionally, because I want to always have CORS for EventSource.
I am curious, what platforms do not support CORS?

**Comment by ncv-dev** [comment]
When the Specification allows for setting the "withCredentials" as an option while dealing with EventSource - it allows for an application to use SSE without CORS.

About the platform, there could be examples like older version of Browsers.  The issue surfaced when attempting to use the Server-Sent Event model in a Qt/QML environment.  QML supports XHR to make a connection, hence by using EvenSource polyfill, can subscribe for events from Servers that support Server-Sent Events.

**Comment by Yaffle** [comment]
well, thouse browsers are very old.
`isCORSSupported` is also used to check if browser supports "XHR 2" (onprogress event).
Because old browsers may not support readyState == 3 (IE 6-7).

Although, I do not mind to change this logic, if EventSource works for your platform (in case you set Transport to XHR)

**Comment by ncv-dev** [comment]
@Yaffle Thanks for the changes.
In the changes, at line 492, is there a typo? if not, could you explain the change -
```javascript
if (isCORSSupported) {  //<-- Should it be NOT
 EventSource.prototype.withCredentials = undefined;
}
```

**Comment by Yaffle** [comment]
To detect EventSource+CORS support `window.EventSource != undefined && ("withCredentials" in window.EventSource.prototype)` could be used.

**Comment by ncv-dev** [comment]
In that case, "EventSource.prototype.withCredentials" should be assigned "undefined" only if "isCORSSupported" is "false".
