### ISSUE TITLE
Timer methods should be access using the "global" parameter similar to how XHR interface is used

### ISSUE THREAD

**Issue by ncv-dev** [Yaffle/EventSource#61]
The `setTimeout()` and `clearTimeout()` methods are normally available in the window context and hence the code makes that assumption.  However, the XHR/XDR interfaces are referenced through `global`, which is a parameter to the immediately invoked function expression (IIFE).

This "issue" is a request to have the timer functions also accessed via `global`, so that it is usable in non-browser JavaScript environment (E.g. QML).

Aside:
A related request would be to see an alternate approach than passing `this` to IIFE.  Say, expecting an object instance by a naming convention - i.e.  instead of `}(this));` using `}(eventSourceConfig));`, where `eventSourceConfig` would fill all the interfaces required by the EventSource polyfill.
[I know this will break existing users :-) but would like to hear opinions]

**Comment by Yaffle** [comment]
What about `Boolean, Error, Math, Number, clearTimeout, encodeURIComponent and setTimeout` ?

**Comment by ncv-dev** [comment]
The standard JavaScript functions governed by the ECMAScript specification are supported in any JavaScript runtime environment.
It is only those functions which are defined as part of W3C specification for HTML that will be missed in a bare JavaScript runtime.

For example, in QML, we do have the support for methods/interfaces you have mentioned.

**Comment by Yaffle** [comment]
if those functions are missed, nothing will work correctly.
So I cannot understand why this needs to be changed.

>However, the XHR/XDR interfaces are referenced through global, which is a parameter to the immediately invoked function expression (IIFE).

This was done not intentionally: the purpose of "IIFE" here is to avoid polluting of the global scope and properties of the global object...
`global` is equal to `this`, and `this` points to global object in global scope normally.
