### ISSUE TITLE
Error processing event (IE9-IE10)

### ISSUE THREAD

**Issue by aledbf** [Yaffle/EventSource#63]
I see this error 
```
 The data necessary to complete this operation is not yet available.
```
eventsource.js, line 192 character 7

latest version from master.

```
    var eventSource = new EventSource(url, {
      withCredentials: true,
      Transport: XMLHttpRequest
    });
```

Any idea how I can provide a better report?
Thanks

Edit: the value received in onEvent is empty

**Comment by aledbf** [comment]
Is possible to reproduce this error request error in this page http://www.debugtheweb.com/test/teststreaming.aspx clicking `Try XMLHttpRequest`
![captura de pantalla 2015-08-13 a las 13 06 13](https://cloud.githubusercontent.com/assets/161571/9254891/625d90d4-41bc-11e5-8a20-7a566d07ae14.png)

**Comment by Yaffle** [comment]
@aledbf , it is not allowed to access `xhr.responseText` in IE 8-9, the `Transport` options was provided to make it possible to use long-polling...
```
        try {
          responseText = xhr.responseText;
        } catch (error) {
          // IE 8 - 9 with XMLHttpRequest
        }
```
This can hide the error, but is it worth of it?

**Comment by aledbf** [comment]
@Yaffle I tried that but it doesn't solve the issue of not processing the events
Thanks for the fast reply.

**Comment by Yaffle** [comment]
@aledbf , try with latest version - XHR was not tested ...

**Comment by aledbf** [comment]
@Yaffle I'm sorry for the delay. It works. I tried http, https, with and without authentication.
Thanks.

**Comment by Yaffle** [comment]
@aledbf , good
