### ISSUE TITLE
Possible Performance regression?

### ISSUE THREAD

**Issue by heikojansen** [Yaffle/EventSource#64]
I was playing around with "eventsource.min.js" from branch master (generated 5 months ago) to figure out if it could avoid using XDomainRequest even in older IE in favor of XMLHttpRequest (because I´m only calling back to my own server so don´t need CORS but want the authentication cookie to be present).

Reading through the source code of the current "eventsource.js" (non-minified) I discovered the "Transport" option and decided to replace my minified older version with the current non-minified version and have a closer look.

After I did that and without changing anything else my app suddenly appeared to slow down for certain events:
All events are supposed to append some text to the page body.
The first and final event work as expected and their content appears in the browser right after they are logged server side.
With intermediate events, however, there suddenly is a significant lag between the time they are logged at the server and when their output appears in the browser.

I´m initializing the object like so:
```javascript
var events = new EventSource('/resultblocks');
events.addEventListener('block', function(ev) {
        document.body.innerHTML += ev.data + '<br/>';
        console.log("chunk " + count++ + ': ' + ev.data.substring(0, 10));
}, false);
events.addEventListener('end', function(ev) {
        document.body.innerHTML += "closing event stream";
        events.close();
}, false);
```
The first and the intermediate events are "block" events.
So far, I ran my tests in IE 11 on Win7 Pro.

My JS knowledge is quite limited so I have no idea which changes that have gone in eventsource.js since eventsource.min.js was generated may cause the differing behavior.

**Comment by Yaffle** [comment]
@heikojansen , I cannot reproduce this lag...
You can try to do next change:
```
      if (!("onprogress" in xhr) || !("ontimeout" in xhr)) {
        xhr.onreadystatechange = onReadyStateChange;
      }
```
Replace this block with:
```
      if (true) {
        xhr.onreadystatechange = onReadyStateChange;
      }
```

**Comment by heikojansen** [comment]
After modifying the current (as of 0a08426) master "eventsource.js" as you suggested the "lag" is indeed gone and it behaves like the older (as of af29ee5) "eventsource.min.js" does.

The behavior *without* the modification shown above seems to be that the invocation of the callback function for an event is delayed until the next event is received. But I´m not totally sure of that and have the gut feeling that there could also / additionally be some IE internal timeout involved.

Probably unrelated but worth mentioning: adding '<meta http-equiv="X-UA-Compatible" content="IE=edge"/>' to the html had no apparent consequences.

**Comment by heikojansen** [comment]
Grrml. I ran a few more tests using "eventsource.js" from "master" as base, but that didn´t help clarify the situation for me.
Here´s the client side code:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>EventSource example</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
</head>
<body>
  <h1>Suchergebnisse</h1>
  <script src="/public/eventsource.min.js"></script>
  <script>
    var es = new EventSource('/resultblock', { Transport: window.XMLHttpRequest });
    var listener = function (ev) {
      var div = document.createElement("div");
      var type = ev.type;
      var msg = "";
      if ( type === "block" ) {
        msg = ev.data;
      }
      else if ( type === "end" ) {
        msg = "closing event stream";
        es.close();
      }
      else if ( type === "error" ) {
        msg = "closing event stream because of server side error";
        es.close();
      }
      else {
        msg = "saw event of type '" + type + "'";
      }
      div.innerHTML += msg;
      document.body.appendChild(div);
    };
    es.addEventListener("open", listener);
    es.addEventListener("message", listener);
    es.addEventListener("error", listener);
    es.addEventListener('block', listener);
    es.addEventListener('end', listener);
  </script>
</body>
</html>
```

First: everything works fine in Firefox 41.0.1, Chromium 46.0.2490.71 and Opera 32.0.1948.69.

* In IE 11 and Edge the behaviour seems to be the same: it works fine with the modification but events are delayed without the modification.
* In IE 10 it works fine *with and without* the modification!
* In IE 9 it works *neither with nor without* the modification; the "open" event is processed immediately (text  "saw event of type 'open'"; appears instantly), all other output in the browser appears later just when the server logs that he has send the final "end" event.

**Comment by Yaffle** [comment]
@heikojansen ,
Thanks, seems, I need to apply this modification.

(in IE8-IE9 "streaming" works only with XDomainRequest, so this is an expected behaviour)

**Comment by heikojansen** [comment]
OK, so for modern browsers the original problem can be considered solved. Thanks!

Regarding IE 8 and 9 we apparently need to decide if either users of these browsers will have to accept a heavily degraded usage experience from our app or if we need to find a workaround for the missing (authentication) cookie when we use the fallback to XDomainRequest. Neither option makes me happy, but I fail to see another solution.

**Comment by heikojansen** [comment]
I´ve tested commit 475236d (though only in IE 11 so far) and it works.

**Comment by Yaffle** [comment]
@heikojansen , thanks
