### ISSUE TITLE
EventSource doesn't work with some browsers

### ISSUE THREAD

**Issue by makseo** [Yaffle/EventSource#65]
Hi,

Maybe someone can explain, where I can find a problem.

In error logs I found, that only with this User-Agents EventSource doesn't work:

```
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko
```

```
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; AskTbORJ/5.15.9.29495; McAfee; BRI/2; GWX:DOWNLOADED; rv:11.0) like Gecko
```

Also, I see, that callback "onopen" and "onclose" works, but "onmessage" not.

Thank you for your help!

**Comment by Yaffle** [comment]
very strange,  if "streaming" is not working "message" events should be fired before "close"

**Comment by Yaffle** [comment]
Can you see "message" events if you close the connection on your server after you send a message?
Do antivirus software cause this?
Is there a workaround?

**Comment by boolow5** [comment]
I had the same issue, but my SSE server was sending event type as 'TICKER' instead of 'message'.

I have changed my js code to:

```
var es = new EventSource(url);
es.addEventListener('TICKER', (e) => {
    console.log('message received', e)
});
```
So make sure the event type you sent from the SSE server matches the event name.

BTW: I use Golang with github.com/mroth/sseserver for the SSE backend
          ```
          SSEServer.Broadcast <- sseserver.SSEMessage{msgType, msgData, channel}
          ```
          You can change the msgType to change the event name
