### ISSUE TITLE
Polyfill vs native EventSource performance/stability

### ISSUE THREAD

**Issue by droidenator** [Yaffle/EventSource#66]
In the past, the recommendation was to use this polyfill for all clients even if their browser had a native implementation. I believe the reasoning was that the native implementations were buggy and issues were not fixed very quickly.

Is this still the recommendation? Are the native implementations of EventSource now more stable/performant than the polyfill? I'm working on a project using SSE and initially planned to only use the polyfill for IE and Edge. Now I'm wondering if I should use the polyfill across the board.

**Comment by Yaffle** [comment]
Well... you should try
Firefox and Chrome are able to detect disconnects now and I do not know about any important bugs.
Currently, EventSource.js replaces native objet in Opera 12 only.
