### ISSUE TITLE
event lost when reposnseText fillls up

### ISSUE THREAD

**Issue by wgemk** [Yaffle/EventSource#69]
There is a size limit of 1024x1024 on the reposnseText. When the reposnseText eventually fills up to exceed 1024x1024, error is detected, the last event is lost and it will reconnect. Is there a way properly way to clear responseText or reconnect before it fills up to avoid losing the last event message? Why is there a limit of 1024x1024?

**Comment by Yaffle** [comment]
to clear the `xhr.responseText`. I don't know about any other way to clear it in IE.
You can close the connection from the server.
