### ISSUE TITLE
Question: Should it throw an error while reconnecting?

### ISSUE THREAD

**Issue by bjarneo** [Yaffle/EventSource#70]
Is there any reason it throws an exception? Is it really an error? 
https://github.com/Yaffle/EventSource/blob/master/eventsource.js#L354

**Comment by Yaffle** [comment]
This is a warning, not an error.
You can remove this line if you want, but it is better to send some "comment" messages every ~30 seconds - they will be used to detect disconnects. This is why `heartbeatTimeout` is here.

**Comment by bjarneo** [comment]
Ah, I see. Thanks for your feedback :)
