### ISSUE TITLE
Origin

### ISSUE THREAD

**Issue by jbarreiros** [Yaffle/EventSource#71]
According to http://www.html5rocks.com/en/tutorials/eventsource/basics/#toc-security, it is suggested that whenever a message arrives, `ev.orgin` should be checked to ensure the data is coming from where you expect it.

When using the polyfill, `ev.origin` is `undefined`. Curious if there is a way to add the `origin`?

I poked through the source code and the only thing I can think of is to use `window.location.origin`, but that is the origin of the document and not necessarily the server serving the EventSource connection.

**Comment by Yaffle** [comment]
what's with origin?

**Comment by jbarreiros** [comment]
Re: what's with origin? Sorry about that, I somehow hit the create issue button before entering my question.

**Comment by Yaffle** [comment]
@jbarreiros , "you should check the 'origin' attribute all the time when receiving messages from window.postMessage()" ( http://krijnhoetmer.nl/irc-logs/whatwg/20111122#l-375 ). 
This is not very useful for messages from an EventSource or a WebSocket.

**Comment by jbarreiros** [comment]
Ah, thank you for the clarification. :+1:

**Comment by Yaffle** [comment]
not at all
