### ISSUE TITLE
EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

### ISSUE THREAD

**Issue by lmkoushik** [Yaffle/EventSource#72]
Event source is working on apache srever. But When I am switching to nginx, it says 
`EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`
I am using PHP and laravel and chrome browser.

I have added 
`header('Content-Type: text/event-stream');`
`header('Cache-Control: no-cache');`
 before the response from server.

**Comment by Yaffle** [comment]
What do you see if you open that URL in your browser?

**Comment by lmkoushik** [comment]
I am getting the below response on console of chrome.
`EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`

**Comment by abzfarah** [comment]
Getting same issue. 
Have you resolved it?

**Comment by Jurigag** [comment]
I have same on IE9. But on other browsers work fine, weird.

**Comment by Yaffle** [comment]
@lmkoushik , @abzfarah , @Jurigag , are you sure the response is correct?
