### ISSUE TITLE
ask from cross site cookie sending

### ISSUE THREAD

**Issue by chinaccj** [Yaffle/EventSource#77]
I am new in Server-Sent Events(SSE). Recently，i need to develop a reminder function .
When user login a website,he can see to unprocessed  things .  I choose SSE to handler this issue.
when user login website A, and make EventSource call to website B(i named SSE server), cookie in website A can not send to SSE server.

code in website A:
 <script src="<%=request.getContextPath() %> /js/eventsource.js"></script>
 <script type="text/javascript">
        function init(){
            document.getElementById('foo').innerHTML = "init data";
        }

```
    var url = "http://localhost:8080/eventconnect";


    var es = new EventSource(url,{withCredentials: true});
    var listener = function (event) {
        ...
    };

    var errorListener = function (event) {
        console.log("error .... "+event.data);
    };
    es.addEventListener("message", listener);
    es.addEventListener("error", errorListener);

</script>
```

 SSE server  web.xml in tomcat to allow cross site visit.
 <filter>
        <filter-name>CorsFilter</filter-name>
        <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
        <async-supported>true</async-supported>
    </filter>
    <filter-mapping>
        <filter-name>CorsFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

**Comment by Yaffle** [comment]
Looks like a normal behaviour of cookies. Why do you want to have a cookie for A at website B?

**Comment by chinaccj** [comment]
I want to push message from SSE server to other website.
SSE server deployed independently which has different domain as other website.
When user login other website,send cookie to SSE server as identity。
I don't know this design has any problem. Could you tell me a right design?

**Comment by Yaffle** [comment]
@chinaccj What if send "the cookie" throught the URL parameters?
