### ISSUE TITLE
EventSource not working with client certificate in IE8

### ISSUE THREAD

**Issue by bugy** [Yaffle/EventSource#78]
If an HTTPS server requires client certificate, then EventSource is not working in IE8 (and most probably IE9), because XDomainRequest doesn't pass client certificates because of "security reasons" (even for the same domain request). 
Using XMLHttpRequest as a Transport doesn't help, because IE8/9 doesn't support streaming (it fails to provide responseText before status reaches 4 (complete)).

Basically this issue is coming from XDomainRequest "limitation", but it worth at least to document, that this case is not working

**Comment by Yaffle** [comment]
Thanks for the information!
