### ISSUE TITLE
"More tasks executed then were scheduled." zone.js error with Angular

### ISSUE THREAD

**Issue by marcelgood** [Yaffle/EventSource#80]
I'm trying to use this shim in an Angular 2 app, but I'm having difficulty in browsers such as Edge. When the app loses connection to the server and no more heartbeats are coming in, the shim starts causing the above error in the latest version (0.0.8). 0.0.7 doesn't seem to have this issue, but it has another issue. It tries to access xhr.readyState in onReadyStateChange, but xhr is undefined in Edge once the connection is lost. If I change line 398 from

`if (xhr.readyState === 4) {`

to 

`if (xhr && xhr.readyState && xhr.readyState === 4) {`

then it seems to all work. I see a similar change in 0.0.8, but unfortunately it reintroduces the above error. I'll manually patch version 0.0.7 for now and run with it, but hopefully you can look into this and make the shim compatible with Angular 2. Thanks. 

UPDATE: Actually, never mind, 0.0.7 has the same issue. It just takes longer for it to occur.

**Comment by Yaffle** [comment]
@marcelgood could you provide something to help to reproduce this?

**Comment by marcelgood** [comment]
@Yaffle thank you for responding. Sorry about the delay, I was out for the holidays. I have to see what I can do. Based on my research, this issue is caused by calling clearTimout on a timer that's already been executed. I suspect that the shim isn't keeping track of the timers that have executed and clears them anyway.

**Comment by Yaffle** [comment]
I cannot reproduce it anyway, sorry. I cannot see this error with Angular 2.

**Comment by marcelgood** [comment]
Just updating and closing the ticket. This issue appears to be resolved in the latest version (0.0.9) and with zone.js 0.7.7.

**Comment by Yaffle** [comment]
good
