### ISSUE TITLE
Publish newest version to npm (including #81)

### ISSUE THREAD

**Issue by TobiasKrogh** [Yaffle/EventSource#82]
Hi,

first of all: great project. I had (nearly) no issue using and integrating it.

I was wondering whether the current state (best with an update to 0.0.9 including the latest minified output - see #81) could be published to npm? I looked through the changes and a project of mine could really benefit from the changes (looking at my bugtracking system). Seems there is already a version 0.0.8 but it is not published on npm.

Best regards

**Comment by Yaffle** [comment]
Hi,
It is published, thanks!
