### ISSUE TITLE
Cache-Control

### ISSUE THREAD

**Issue by xogeny** [Yaffle/EventSource#83]
Note that with Chrome, it is important to add `no-store` to the `Cache-Control` header.  I see that in the code you've commented out the `Cache-Control` header (with some comment about a Chrome bug).  But I think the solution might be to add:

```
Cache-Control: no-store, no-cache
```

This is important with Chrome in particular because it locks the cache based on URL (ignoring `Accept` header).  If you open a connection that is persistent (i.e., an EventSource), you'll end up stall subsequent requests to the same URL by 20 seconds waiting for the cache lock to expire unless you add the `no-store`.

**Comment by Yaffle** [comment]
Thanks for the suggestion, but I am not using "Cache-control" as it is not a allowed for simple cross origin requests.

**Comment by xogeny** [comment]
I'm not sure what you mean by not allowed.  I stopped using the `EventSource` code because it was not adequate for persistent connections (for the reasons I've outlined).  It is, of course, up to you to decide whether to address this.  But keep in mind that the problem is there, users will have problems on Chrome because of Chrome's cache locking.

**Comment by Yaffle** [comment]
@xogeny, are you talking about response header or request header?

So do you want me to update my examples of server side code?

**Comment by Yaffle** [comment]
@xogeny, I cannot reproduce it - "Cache-control: no-cache" works for me.

**Comment by xogeny** [comment]
IIRC (this is an old issue), in order to see the issue you'd need to create two different instances in Chrome tracking the same URL and leave the connection open.  What will happen is that Chrome will open the first one, but it will lock the cache for it.  But since the request never terminates (it just stays open), the cache stays locked.  Then if you open with a second connection (**even in a different tab**), Chrome will block the second connection because the cache is locked.  So if you say "it works" for that case, you have nothing to worry about.  But if it doesn't work (if the second connection hangs for 10 seconds), then you'll create a lot of misery for any user who comes along and tries to use the library because they will probably be completely perplexed why it doesn't work.  Running two versions of an application in two different tabs is not such an unusual situation when testing.  That was the situation I was in and I eventually dug into it enough to identify both the problem and the solution.

**Comment by Yaffle** [comment]
@xogeny,
Thanks, finally I see it.
I need to use XMLHttpRequest with same URL in both tabs.
And, if I use request header Cache-control: no-cache - it helps.
If I response with "Cache-control: no-store" on server side - it helps too.

**Comment by Yaffle** [comment]
So should I use "no-store" everywhere on server side?

**Comment by xogeny** [comment]
If I recall correctly, I added it only client side exactly as I showed earlier in this issue.

**Comment by xogeny** [comment]
Actually, I think I'm wrong.  I think it was server side (both).

**Comment by Yaffle** [comment]
@xogeny, Thanks, I have updated the code.
