### ISSUE TITLE
JS files not located in web-safe directory

### ISSUE THREAD

**Issue by brandonkelly** [Yaffle/EventSource#84]
The JS scripts in this repo should be located in a directory that would be be safe to publish in a web-accessible location. They are not currently, because they live alongside that `php/` directory that is obviously not safe to publish.

This is an issue because, as an example, the library might be getting included in a [Yii](http://www.yiiframework.com/) application as an [asset bundle](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html), which publishes an entire source directory, and then registers `<script>` tags in the rendered HTML pointing to the JS files within the published directory.

The JS scripts should be moved into a `src/` subdirectory, or something like that, which is safe to be published in its entirety into  a web-accessible location.

**Comment by Yaffle** [comment]
Isn't there way to not move those files and to avoid publishing of `php/`?

**Comment by brandonkelly** [comment]
@Yaffle Not in certain situations, such as the one described above.

**Comment by brandonkelly** [comment]
@Yaffle Thanks! 👍

**Comment by Yaffle** [comment]
@brandonkelly Thanks for the pull request
