### ISSUE TITLE
addEventListener to custom event

### ISSUE THREAD

**Issue by dellow88** [Yaffle/EventSource#86]
Hey,
Not sure if this is a bug or if I am doing something wrong however I am using EventSource with PHP (currently MAMP) and when I define a custom event I cant use standard addEventListener functionality to run a function.

PHP:
```
echo "id: -1 \n";
echo "event: success \n";
echo "data: success\n\n";
```

JS:
`es.addEventListener("success", processingComplete);`
```
var processingComplete = function (e) {
		console.log("in");
		$('#result').innerHtml = e.data;
		console.log(e);
		console.log("Connection Closed");
		e.target.close();
	};
```

I use a listener var for all other events (open, message, error) and output works accordingly however as soon as I reach the end of my file and send the custom event it does nothing. I have looked in the headers of both chrome and safari (MacOS) and I can see the event being sent in the EventStream column (under Network > {PageName} <webpage name> > EventStream (see attached)) but the event listener just wont hook onto it.

I read that this polyfill overwrites the standard Event Stream so is this the reason and if so what is the work around?

Thanks in advance

<img width="1275" alt="screen shot 2017-04-11 at 19 00 22" src="https://cloud.githubusercontent.com/assets/27299692/24923364/337fe5b2-1ee9-11e7-92b5-c56eb1f19254.png">

**Comment by Yaffle** [comment]
@dellow88 , try to remove the extra space after the event name:
-echo "event: success \n";
+echo "event: success\n";

**Comment by dellow88** [comment]
Wow - well that's embarrassing, not to mention a waste of a couple of hours!
Sorry and thanks for pointing out my stupidity.
