### ISSUE TITLE
eventsource not always reconnecting

### ISSUE THREAD

**Issue by jkarneges** [Yaffle/EventSource#88]
EventSource reconnects if a connection is lost, and will keep retrying if it fails to reach the server. However, if the server responds with an error (e.g. 500 status) then EventSource will stop reconnecting. I'm testing this on recent browsers (Chrome 59, Firefox 54).

As some server errors could be temporary, clients need a way to reconnect in this situation and I wonder how best to handle that. It looks like `readyState == 2` when EventSource gives up, so the client's `onerror` callback could inspect that value and recreate the EventSource object if needed. Of course this means basically reimplementing the reconnect process, having to set a timer, and record the most recent event ID so it can be provided in a `lastEventId` parameter of the new object.

Does that sound right? If so, it may be a good idea for someone to develop a wrapper project around EventSource for better reconnect handling. I wonder if that handling should go into this polyfill project, and then it should always replace the native object.

**Comment by def324** [comment]
Take a look at #24 - Older versions of this EventSource polyfill used to do what you are looking for, however at some point it changed to be more compliant with the official standard. I had plans to maintain a fork that covers this scenario but never got around to it. If you are comfortable using an older version (pre December 2014) that might solve your problem. I'm doing this currently without any issues, however it is in a fairly isolated environment. 

Personally I'd still love to see this to be an optional setting as I think there are certainly valid use cases where a reconnect on 500 makes sense.

**Comment by jkarneges** [comment]
I've gone ahead and made a wrapper, that could be used with either the polyfill or native:
https://github.com/fanout/reconnecting-eventsource

I figure if the goal of the polyfill is to be standards compliant, then it's probably best to solve this issue externally, until the standard is updated.
