### ISSUE TITLE
Both cases of a conditional run the same code

### ISSUE THREAD

**Issue by rajsite** [Yaffle/EventSource#90]
The following conditional: https://github.com/Yaffle/EventSource/blob/16a5f08334cdc85b27009d8876a19b246187b4b2/src/eventsource.js#L115

```javascript
if (this.xhr.status === 0) {
  this.onFinish();
} else {
  this.onFinish();
}
```

Appears to run the same function in both cases, is this intentional?

**Comment by Yaffle** [comment]
No, the branches had different code previously.
