### ISSUE TITLE
Trancated xhr response in Edge - resolved via hackery!

### ISSUE THREAD

**Issue by georgekaz** [Yaffle/EventSource#91]
Hi,
I had an issue that Edge would randomly truncate my initial long response after the connection, I think potentially related to this open bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6346939/

It's really odd because in XHRTransportInternal.prototype.onStart if you console.log(this) and look at xhr, the response is correct and not truncated, but if you console.log(this.xhr) the response is truncated to around 630 chars (exact length varies between messages).

I think it's a timing issue, and my work around is to move the contents of XHRTransportInternal.prototype.onProgress to another function which is then called like this:

XHRTransportInternal.prototype.onProgress = function () {
	if (!UAisEdge){
		XHRTransportInternalProgress(this);
	} else {
		setTimeout(XHRTransportInternalProgress, 1, this);
	}
  };

  function XHRTransportInternalProgress (xhrtransportinternal) {
	xhrtransportinternal.onStart();
    if (xhrtransportinternal.state === 2 || xhrtransportinternal.state === 3) {
    	xhrtransportinternal.state = 3;
      var responseText = "";
      try {
        responseText = xhrtransportinternal.xhr.responseText;
      } catch (error) {
        // IE 8 - 9 with XMLHttpRequest
      }
      var chunkStart = xhrtransportinternal.charOffset;
      var length = responseText.length;
      for (var i = xhrtransportinternal.offset; i < length; i += 1) {
        var c = responseText.charCodeAt(i);
        if (c === "\n".charCodeAt(0) || c === "\r".charCodeAt(0)) {
        	xhrtransportinternal.charOffset = i + 1;
        }
      }
      xhrtransportinternal.offset = length;
      var chunk = responseText.slice(chunkStart, xhrtransportinternal.charOffset);
      xhrtransportinternal.onProgressCallback.call(xhrtransportinternal.thisArg, chunk);
    }
  };

Horrible hackery I know, but it works. I'm sure you can come up with a more elegant solution. I've attached my version of the file.
[eventsource.yaffle.js.zip](https://github.com/Yaffle/EventSource/files/1197511/eventsource.yaffle.js.zip)

Thanks

**Comment by Yaffle** [comment]
@georgekaz, https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12224510/ - is it about this issue?

**Comment by Yaffle** [comment]
There is another block in the code to check `responseText` every 500 ms:
```
    if (("readyState" in this.xhr) && global.opera != undefined) {
      // workaround for Opera issue with "progress" events
      this.timeout = setTimeout(function () {
        that.onTimeout0();
      }, 0);
    }
```
I think, it is better to use it for Edge.

**Comment by georgekaz** [comment]
Yes, could be related to that ms issue as it's a new problem as far as I know. How would I use the other block you mention in this case? If they've fixed the edge bug in v16 I might just wait til they roll that out and switch back to your trunk version.
