### ISSUE TITLE
a way to know if the server should send padding

### ISSUE THREAD

**Issue by jkarneges** [Yaffle/EventSource#96]
Hi,

Today I wondered about making the 2048 bytes of padding optional on our server, but I thought it would be even better if the server could autodetect when it needs to use it, so that no option is needed at all. It looks like the polyfill includes an `r` query parameter, which I assume the native EventSource wouldn't, and so maybe the server could just look for that and send padding if it is present.

Another idea would be to have the polyfill send something more explicit, like a `padding=true` query param.

What do you think?

**Comment by gobengo** [comment]
IMO best to whitelist the user agents that require it. My understanding is it's more or a less a bug that some user agents require it before passing data long to listeners.

**Comment by Yaffle** [comment]
IE < 10 and Chrome < 13.
Those web browsers are not very popular now.

**Comment by Yaffle** [comment]
https://github.com/Yaffle/EventSource/commit/dfb705e6606c4660241c24047a31abfc1bb7c49a
