### ISSUE TITLE
Expose EventSource even if it is supported by browser

### ISSUE THREAD

**Issue by janober** [Yaffle/EventSource#98]
Hello,

I did run into an issue with the native EventSource implementation. When the connection gets refused for some reason (like with 401 because authorization failed) the native one simply errors but no information is given why it did fail. Did not find any way to get the status code out. So I was wondering if you would merge a pull request which would always expose this implementation (but not overwrite by default like it currently does) as something like "EventSourcePolyfill" and which would add the response code to the error.

Is also possible that I overlooked something and the native implementation allows something like that already. Then it would be great to get a tip. Thanks!

**Comment by Yaffle** [comment]
Hello, it is already exposed - EventSourcePolyfill , 
Well... not sure if npm release / minified file has this...

**Comment by janober** [comment]
Ah yes thanks. Can see it in the Github code.

You are right in the latest released version that is still missing and why I could not find it. Any plans of releasing a new version soon?

**Comment by Yaffle** [comment]
I have just tried to publish it, please check.

**Comment by janober** [comment]
Great thanks! Works fine. Closing.
