### ISSUE TITLE
Send headers Authorization

### ISSUE THREAD

**Issue by kurcob84** [Yaffle/EventSource#99]
Hi,

its seems that it is not possible to set header Authorization? 

`var es = new EventSource(api.root + "auth/profil/notificationEventSource", {
	withCredentials: true,
	headers: {
		Authorization: "Bearer " + user.token
	}
});`

Or how it will be right?

THX a lot

**Comment by Yaffle** [comment]
Try with `var es = new EventSourcePolyfill(...)`

**Comment by kurcob84** [comment]
It works ;)

**Comment by Yaffle** [comment]
good
